[display]
compact = false
use_pager = true

[style.description]
foreground = "yellow"

[style.command_name]
foreground = "green"

[style.example_text]
foreground = "white"

[style.example_code]
foreground = "magenta"

[style.example_variable]
foreground = "blue"
underline = true

[updates]
auto_update = true

[directories]
cache_dir = "/Users/miked/.local/share/tealdeer"
custom_pages_dir = "/Users/miked/.local/share/tealdeer/custom-tldr-pages"
