#!/usr/bin/env bash

alias ll="ls -lAFLhG"
alias ls="ls -AFLG"
alias ldot='ls -ld .* --group-directories-first'
colorflag="-G"
alias l="ls -lF ${colorflag}" # all files, in long format
alias la="ls -laF ${colorflag}" # all files inc dotfiles, in long format
alias lsd='ls -lF ${colorflag} | grep "^d"' # only directories

alias ~="cd ~"
alias -- -="cd -"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......='cd ../../../../..'
alias .......='cd ../../../../../..'
alias ........='cd ../../../../../../..'

alias h='history'

# Always show disk usage in a human readable format
alias df="df --human-readable"
alias du="du --human-readable"
alias free="free -human "

# mimic vim functions
alias :q='exit'

# source bashrc from anywhere
alias src="source $HOME/.bashrc"

# Fuck - rerun previous prepend sudo
alias fuck='sudo $(history -p \!\!)'

# trash: https://github.com/sindresorhus/macos-trash
command -v trash >/dev/null 2>&1 && alias rm="trash"

# Enable aliases to be sudo’ed
alias sudo="sudo "
alias please="sudo "

# Make watch work with aliases
alias watch="watch " 

# Reload the shell (i.e. invoke as a login shell)
alias reload="exec $SHELL -l"

# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'

alias now="date +'%T'"
alias nowtime=now
alias nowdate="date +'%d-%m-%Y'"
# Get week number
alias week="date +%V"

# git shit
alias glone="git clone --depth 1 "

# Changed your .gitignore _after_ you have added / committed some files?
# run `gri` to untrack anything in your updated .gitignore
# Put this in your .zshrc file
alias gri="git ls-files --ignored --exclude-standard | xargs -0 git rm -r"

alias dotgit='/usr/bin/git --git-dir=/Users/miked/.dotfiles/ --work-tree=/Users/miked'

# Folders
alias projects="$HOME/Dev"
alias documents="$HOME/Documents"
alias downloads="$HOME/Downloads"
alias dotfiles="$HOME/.config"

alias mv="mv -iv"
alias cp="cp -iv"
alias ln="ln -iv"
alias mkdir="mkdir -pv"

alias perm='stat --printf "%a %n \n "' # Show permission of target in number
alias 000='chmod 000'                  # ---------- (usr grp oth)
alias 640='chmod 640'                  # -rw-r-----
alias 644='chmod 644'                  # -rw-r--r--
alias 755='chmod 755'                  # -rwxr-xr-x
alias 775='chmod 775'                  # -rwxrwxr-x
alias mx='chmod a+x'                   # ---x--x--x
alias ux='chmod u+x'                   # ---x------


# become root #
alias root='sudo -i'
alias su='sudo -i'

alias sha1="openssl sha1"

# colorize diff output - install colordiff package
alias diff="colordiff"

# Make mount command output pretty and human readable format
alias mount="mount |column -t"

# Resume wget by default
## this one saved by butt so many times ##
alias wget="wget -c"

# Download file and save it with filename of remote file
alias get="curl -O -L"

# bat - https://github.com/sharkdp/bat
# alias bat="bat --style=numbers,changes "

# Always colorize output by default
alias fd='fd --color always '

alias exall="exa --long --all --header --git --icons --classify --group-directories-first --time-style=long-iso --group --color=always --binary --links --accessed --created --modified"
alias exalx="exa --long --all --header --git --icons --classify --group-directories-first --time-style=long-iso --group --color=always --binary --links --created --extended"
alias exat="exa --tree --all --classify --icons"

alias ag="ag \
    --hidden \
    --follow \
    --smart-case \
    --numbers \
    --color-match '1;31' \
    --color-path '0;37' \
    --color-line-number '1;33'"

# Misc Network Shit ###########################################################

# IP addresses
alias myip='ifconfig en0 | grep inet | grep -v inet6 | cut -d ' ' -f2'
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en0"
alias ips="ifconfig -a | perl -nle'/(\d+\.\d+\.\d+\.\d+)/ && print $1'"
# alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# Enhanced WHOIS lookups
alias whois="whois -h whois-servers.net"

# View HTTP traffic
alias sniff="sudo ngrep -d 'en1' -t '^(GET|POST) ' 'tcp and port 80'"
alias httpdump="sudo tcpdump -i en1 -n -s 0 -w - | grep -a -o -E \"Host\: .*|GET \/.*\""

# Control output of ping
# Stop after sending count ECHO_REQUEST packets #
alias ping="ping -c 5"
# Do not wait interval 1 second, go fast #
alias fastping="ping -c 100 -s.2"

# Use netstat command to quickly list all TCP/UDP port on the server
alias ports="netstat -tulanp"

# Misc Mac Shit ###############################################################

# Empty the Trash on all mounted volumes and the main HDD.
# Also, clear Apple’s System Logs to improve shell startup speed.
# Finally, clear download history from quarantine. https://mths.be/bum
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl; sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* 'delete from LSQuarantineEvent'"

# Get OS X Software Updates, and update installed Ruby gems, Homebrew, npm, and their installed packages
alias update='sudo softwareupdate -i -a; brew update; brew upgrade; brew cleanup; npm update npm -g; npm update -g; sudo gem update --system; sudo gem update'

# Show/hide hidden files in Finder
alias showdots="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hidedots="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# Hide/show all desktop icons (useful when presenting)
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

# Disable Spotlight
alias spotlightoff="sudo mdutil -a -i off"
# Enable Spotlight
alias spotlighton="sudo mdutil -a -i on"

# Recursively delete `.DS_Store` files
alias cleanup="find . -name '*.DS_Store' -type f -ls -delete"

# Lock the screen (when going AFK)
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"

# Edit hosts file in Sublime
alias hosts='sudo $EDITOR /etc/hosts'

# Flush Directory Service cache
alias flush="dscacheutil -flushcache && killall -HUP mDNSResponder"

# Clean up LaunchServices to remove duplicates in the “Open With” menu
alias lscleanup="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user && killall Finder"

# Canonical hex dump; some systems have this symlinked
command -v hd > /dev/null || alias hd="hexdump -C"

# OS X has no `md5sum`, so use `md5` as a fallback
command -v md5sum > /dev/null || alias md5sum="md5"

# OS X has no `sha1sum`, so use `shasum` as a fallback
command -v sha1sum > /dev/null || alias sha1sum="shasum"

# Trim new lines and copy to clipboard
alias c="tr -d '\n' | pbcopy"


# My Misc Shit ################################################################

# add Sublime Text terminal command
# alias subl="/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl"

# PlistBuddy alias, because sometimes `defaults` just doesn’t cut it
alias plistbuddy="/usr/libexec/PlistBuddy"

# Stuff I never really use but cannot delete either because of http://xkcd.com/530/
alias stfu="osascript -e 'set volume output muted true'"
alias pumpitup="osascript -e 'set volume output volume 100'"

# Kill all the tabs in Chrome to free up memory
# [C] explained: http://www.commandlinefu.com/commands/view/402/exclude-grep-from-your-grepped-output-of-ps-alias-included-in-description
alias chromekill="ps ux | grep '[C]hrome Helper --type=renderer' | grep -v extension-process | tr -s ' ' | cut -d ' ' -f2 | xargs kill"

alias DT='tee ~/Desktop/terminalOut.txt'    # DT:           Pipe content to file on MacOS Desktop
alias numFiles='echo $(ls -1 | wc -l)'      # numFiles:     Count of non-hidden files in current dir
