#!/usr/bin/env bash
# inputrc config
# ---
# This file controls the behavior of line input editing for
# programs that use the GNU Readline library.  Existing
# programs include FTP, Bash, and GDB.
#
# You can re-read the inputrc file with C-x C-r.
# Lines beginning with '#' are comments.
# http://ss64.com/bash/syntax-inputrc.html
# -----------------------------------------------------------------------------
# First, include any system-wide bindings and variable
# assignments from /etc/Inputrc
# $include /etc/inputrc

# Disable beeping and window flashing
set bell-style none

# Perform file completion in a case insensitive fashion
set completion-ignore-case on

# Treat hyphens and underscores as equivalent
set completion-map-case on

# Show me up to 5,000 completion items, don't be shy
set completion-query-items 5000

# If set to 'on', when listing completions, Readline displays the common prefix of the set of possible completions using a different color. The color definitions are taken from the value of the LS_COLORS environment variable. The default is 'off'.
# Color the common prefix
set colored-completion-prefix on

# on menu-complete, first display the common prefix, then cycle through the
# options when hitting TAB
set menu-complete-display-prefix on

# Show all autocomplete results at once
set page-completions off

# Show multiple completions on first tab press
set show-all-if-ambiguous on

# ?
set show-all-if-unmodified on

# Be more intelligent when autocompleting by also looking at the text after
# the cursor. For example, when the current line is "cd ~/src/mozil", and
# the cursor is on the "z", pressing Tab will not autocomplete it to "cd
# ~/src/mozillail", but to "cd ~/src/mozilla". (This is supported by the
# Readline used by Bash 4.)
# Don't re-complete already completed text in the middle of a word
set skip-completed-text on

# Don't display control characters like ^C if I input them
set echo-control-characters Off

# Expand tilde to full path on completion
set expand-tilde On

# Preserve caret position while browsing through history lines
set history-preserve-point On

# When completing directories, add a trailing slash
set mark-directories On

# Do the same for symlinked directories
set mark-symlinked-directories on

# Show extra file information when completing, like `ls -F` does
set visible-stats on

# If set to 'on', Readline displays possible completions using different colors to indicate their file type. The color definitions are taken from the value of the LS_COLORS environment variable. The default is 'off'.
# Color files by types
# Note that this may cause completion text blink in some terminals, e.g. xterm
set colored-stats on

# Do not autocomplete hidden files unless the pattern explicitly begins with a dot
set match-hidden-files off

# If there are more than 200 possible completions for a word, ask to show them all
set completion-query-items 200

# Use the `vi` set of key bindings (default is `emacs`).
set editing-mode vi

# Allow UTF-8 input and output, instead of showing stuff like $'\0123\0456'
set input-meta on
set output-meta on
set convert-meta off

# Use Alt/Meta + Delete to delete the preceding word
"\e[3;3~": kill-word

# Use the text that has already been typed as the prefix for searching through
# commands ↑ ↓ (basically more intelligent Up/Down behavior)
"\e[A": history-search-backward
"\e[B": history-search-forward

# macOS Option + Left/Right arrow keys to move the cursor wordwise
"\e\e[C": forward-word
"\e\e[D": backward-word